[package]
name = "zk-headstash"
version = {workspace = true}
edition = "2021"

[features]
default = ["circuit", "multicore", "std", "interface"]
interface = ["headstash-randomness"]
multicore = ["halo2_proofs?/multicore"]
circuit = ["dep:halo2_gadgets", "dep:halo2_proofs", "std"]
std = ["core2/std", "group/wnaf-memuse" , "dep:halo2_proofs","reddsa/std"]
dev-graph = ["halo2_proofs?/dev-graph", "image", "plotters"]
rpc = []

[dependencies]
headstash-randomness  = { workspace = true,  optional = true }
halo2_gadgets  = { workspace = true, optional = true }
halo2_proofs  = { workspace = true , optional = true}
halo2-base  = { workspace = true }
anybuf  = { workspace = true }

# plume_rustcrypto  = { workspace = true }

commonware-runtime   = { workspace = true }
aes = "0.8"
base64  = { workspace = true }
bitvec = { workspace = true, default-features = false }
blake2b_simd = { workspace = true, default-features = false }
blake3  = { workspace = true }
core2 = { workspace = true, default-features = false, features = ["alloc"] }
cosmwasm-std = { workspace = true }
ff  = {workspace = true }
fpe = { workspace = true, default-features = false, features = ["alloc"] }
hex = {workspace = true }
lazy_static  = {workspace = true }
memuse = { workspace = true, default-features = false }
num-bigint  = {workspace = true }
num-traits = {workspace = true }
pasta_curves  = {workspace = true }
reddsa = { workspace = true, default-features = false }
rand = {workspace = true }
rand_core = { workspace = true, default-features = false }
rayon = {workspace = true }
secp256k1  = {workspace = true}
prost = { workspace = true }
tonic = {workspace = true }
tonic-prost = {workspace = true }
group = {workspace = true}

sinsemilla = {workspace = true }
image  = {workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] } 
serde_json  = {workspace = true }
subtle = { workspace = true, default-features = false }
zip32 = { workspace = true, default-features = false }
proptest = { workspace = true, optional = true }
nonempty = { workspace = true, default-features = false }
zcash_note_encryption = "0.4"
incrementalmerkletree = "0.8.1"
zcash_spec = {workspace = true }
visibility = {workspace = true }

# Logging
tracing = { workspace = true, default-features = false }
# Developer tooling dependencies
plotters = { workspace = true, optional = true }
# Boilerplate
getset = {workspace = true }
 
[dev-dependencies]
criterion = "0.4" # 0.5 depends on clap 4 which has MSRV 1.70
halo2_gadgets = { workspace = true,  version = "0.3.1", features = ["test-dependencies"] }
hex = "0.4"
proptest = ">=1.0.0, <1.7.0"
zcash_note_encryption = { version = "0.4", features = ["pre-zip-212"] }
incrementalmerkletree = { version = "0.8.1", features = ["test-dependencies"] }
shardtree = "0.6"

 