#!/bin/bash

fmt:
	cargo fmt --all --check
schema:
	sh scripts/sh/schema-and-codegen.sh

lint:
	cargo clippy --fix --tests -- -D warnings
   
build:
  docker run --rm -t -v "$(pwd)":/code \
    --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
    --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
    cosmwasm/workspace-optimizer-arm64:0.17.0

	
 
test:
    cargo test --locked

# publish:
#     #!/usr/bin/env bash
#     crates=(
 
#     )

#     for crate in "${crates[@]}"; do
#       cargo publish -p "$crate"
#       echo "Sleeping before publishing the next crate..."
#       sleep 30
#     done

