[package]
name = "zk-crates"
version = "0.1.0"
edition = "2021"

[dependencies]
headstash-randomness = { path = "../libs/randomness" }
serde = {version = "1.0.228",features = ["derive"]  } 
serde_json = "1.0.145"
lazy_static = "1"
memuse = { version = "0.2.2", default-features = false }
core2 = { version = "0.3", default-features = false, features = ["alloc"] }
rayon = "1.11.0"

## key related
ff = "0.13"
pasta_curves = "0.5"
zip32 = { version = "0.2.0", default-features = false }
k256 = { version = "0.13.4", features = ["hash2curve"] }
plume_rustcrypto = {path = "./submodules/zk-nullifier-sig/rust-k256"}
elliptic-curve = { version =  "0.13.8", features = ["hash2curve"] }
redjubjub = { version = "0.8", default-features = false }
jubjub = { version = "0.10", default-features = false, features = ["alloc"] }
bip39 = "2.2.0"
hkdf = "0.12.4"
secp256k1 = "0.31.1"

halo2_gadgets = { path = "./submodules/halo2/halo2_gadgets",  version = "0.3.1",features = ["test-dev-graph","test-dependencies"]  } 
halo2_proofs = { path = "./submodules/halo2/halo2_proofs", version = "0.3.1" ,features = ["test-dev-graph","gadget-traces", "dev-graph"]  } 
halo2-ecc = {path = "./submodules/halo2-lib/halo2-ecc"}
halo2-base = {path = "./submodules/halo2-lib/halo2-base"}

num-bigint = "0.4.6"
bitvec = { version = "1", default-features = false }

cosmwasm-std = { version = "3.0.0"  }

## randomness-generation
rand = "0.8"
rand_core = { version = "0.6", default-features = false }
group = "0.13"

## hashing/encoding/encryption
subtle = { version = "2.3", default-features = false }
hex = "0.4.3"
hex-literal = "1.0.0"
poseidon-rs = "0.0.8"
blake2b_simd = { version = "1", default-features = false }
base64 = "0.22.1"
blake3 = "1.8.2"
sinsemilla = "0.1.0"
aes = "0.8"
fpe = { version = "0.6", default-features = false, features = ["alloc"] }

# Developer tooling dependencies
plotters = { version = "0.3.0", default-features = false }
bls12_381 = "0.8.0"
num-traits = "0.2.19"

[dev-dependencies]

