[package]
name = "cw-headstash"
version = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
library = []
interface = ["dep:cw-orch"]

[dependencies]
anyhow  = { workspace = true }
ark-bls12-381 = { workspace = true }
ark-ec   = { workspace = true }
ark-ff  = { workspace = true }
ark-serialize = { workspace = true }
blake3 = { workspace = true }
cosmwasm-schema  = { workspace = true }
cosmwasm-std  = { workspace = true, features = ["cosmwasm_2_0"] }
cw-orch = { workspace = true, optional = true }
cw-ownable = { workspace = true }
cw-storage-plus  = { workspace = true }
halo2_proofs  = { workspace = true }
hex  = { workspace = true }
pasta_curves = { workspace = true }
rand_core  = { workspace = true }
serde  = { workspace = true }
sha2  = { workspace = true }
terp-auth  = { workspace = true }
zk-headstash  = { workspace = true }

[dev-dependencies]
cw-headstash-manifold = { workspace = true }
cw-multi-test = { workspace = true }
