[package]
name = "zk-headstash"
version = { workspace = true }
edition = "2021"

[features]
default = ["circuit", "multicore", "std", "interface"]
circuit = ["dep:halo2_gadgets", "dep:halo2_proofs", "std"]
interface = ["std", "circuit", "dep:cw-orch"]
multicore = ["halo2_proofs?/multicore"]
std = ["core3/std", "group/wnaf-memuse", "reddsa/std"]
# dev-graph = ["halo2_proofs?/dev-graph", "image", "plotters"]
rpc = []
test-dependencies = []
dev-graph = []

[dependencies]
aes = { workspace = true }
base64  = { workspace = true }
bitvec = { workspace = true, default-features = false }
blake2b_simd = { workspace = true, default-features = false }
blake3  = { workspace = true }
core3 = { workspace = true, default-features = false, features = ["alloc"] }
cosmwasm-std = { workspace = true, features = ["zk"] }
cw-orch  = { workspace = true, optional = true }
ff  = { workspace = true }
fpe = { workspace = true, default-features = false, features = ["alloc"] }
# plotters = { workspace = true, optional = true }
getset = { workspace = true }
group = { workspace = true }
halo2-base  = { workspace = true }
halo2_gadgets  = { workspace = true, optional = true }
halo2_proofs  = { workspace = true, optional = true }
headstash-randomness  = { workspace = true }
hex = { workspace = true }
incrementalmerkletree = "0.8.1"
lazy_static  = { workspace = true }
memuse = { workspace = true, default-features = false }
nonempty = { workspace = true, default-features = false }
num-bigint  = { workspace = true }
num-traits = { workspace = true }
pasta_curves  = { workspace = true }
proptest = { workspace = true, optional = true }
prost = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
rayon  = { workspace = true }
#rayon = { workspace = true, optional = true }
reddsa = { workspace = true, default-features = false }
secp256k1  = { workspace = true }
serde = { workspace = true, features = ["derive"] } 
serde_json  = { workspace = true }
sinsemilla = { workspace = true }
subtle = { workspace = true, default-features = false }
tracing = { workspace = true, default-features = false }
visibility = { workspace = true }
zcash_note_encryption = "0.4"
zcash_spec = { workspace = true }
zip32 = { workspace = true, default-features = false }
zk-cosmwasm = { workspace = true }

[dev-dependencies]
halo2_gadgets = { workspace = true, features = ["test-dependencies"] }
hex  = { workspace = true }
incrementalmerkletree  = { workspace = true }
proptest  = { workspace = true }
shardtree = { workspace = true }
zcash_note_encryption  = { workspace = true }
