use ff::Field;
use halo2_proofs::{
    circuit::{AssignedCell, Chip, Layouter, Region, SimpleFloorPlanner, Value},
    pasta::{pallas, EqAffine, Fp},
    plonk::{
        Advice, Circuit, Column, ConstraintSystem, Error, Fixed, Instance, Selector, TableColumn,
    },
    poly::Rotation,
};
use rand_core::OsRng;
use std::marker::PhantomData;

// ANCHOR: instructions
trait NumericInstructions<F: Field>: Chip<F> {
    /// Variable representing a number.
    type Num;

    /// Loads a number into the circuit as a private input.
    fn load_private(&self, layouter: impl Layouter<F>, a: Value<F>) -> Result<Self::Num, Error>;

    /// Loads a number into the circuit as a fixed constant.
    fn load_constant(&self, layouter: impl Layouter<F>, constant: F) -> Result<Self::Num, Error>;

    /// Returns `c = a * b`.
    fn mul(
        &self,
        layouter: impl Layouter<F>,
        a: Self::Num,
        b: Self::Num,
    ) -> Result<Self::Num, Error>;

    /// Exposes a number as a public input to the circuit.
    fn expose_public(
        &self,
        layouter: impl Layouter<F>,
        num: Self::Num,
        row: usize,
    ) -> Result<(), Error>;
}
// ANCHOR_END: instructions

// ANCHOR: chip
/// The chip that will implement our instructions! Chips store their own
/// config, as well as type markers if necessary.
struct FieldChip<F: Field> {
    config: FieldConfig,
    _marker: PhantomData<F>,
}
// ANCHOR_END: chip

// ANCHOR: chip-config
/// Chip state is stored in a config struct. This is generated by the chip
/// during configuration, and then stored inside the chip.
#[derive(Clone, Debug)]
struct FieldConfig {
    /// For this chip, we will use two advice columns to implement our instructions.
    /// These are also the columns through which we communicate with other parts of
    /// the circuit.
    advice: [Column<Advice>; 2],

    /// This is the public input (instance) column.
    instance: Column<Instance>,

    // We need a selector to enable the multiplication gate, so that we aren't placing
    // any constraints on cells where `NumericInstructions::mul` is not being used.
    // This is important when building larger circuits, where columns are used by
    // multiple sets of instructions.
    s_mul: Selector,
}

impl<F: Field> FieldChip<F> {
    fn construct(config: <Self as Chip<F>>::Config) -> Self {
        Self {
            config,
            _marker: PhantomData,
        }
    }

    fn configure(
        meta: &mut ConstraintSystem<F>,
        advice: [Column<Advice>; 2],
        instance: Column<Instance>,
        constant: Column<Fixed>,
    ) -> <Self as Chip<F>>::Config {
        meta.enable_equality(instance);
        meta.enable_constant(constant);
        for column in &advice {
            meta.enable_equality(*column);
        }
        let s_mul = meta.selector();

        // Define our multiplication gate!
        meta.create_gate("mul", |meta| {
            // To implement multiplication, we need three advice cells and a selector
            // cell. We arrange them like so:
            //
            // | a0  | a1  | s_mul |
            // |-----|-----|-------|
            // | lhs | rhs | s_mul |
            // | out |     |       |
            //
            // Gates may refer to any relative offsets we want, but each distinct
            // offset adds a cost to the proof. The most common offsets are 0 (the
            // current row), 1 (the next row), and -1 (the previous row), for which
            // `Rotation` has specific constructors.
            let lhs = meta.query_advice(advice[0], Rotation::cur());
            let rhs = meta.query_advice(advice[1], Rotation::cur());
            let out = meta.query_advice(advice[0], Rotation::next());
            let s_mul = meta.query_selector(s_mul);

            // Finally, we return the polynomial expressions that constrain this gate.
            // For our multiplication gate, we only need a single polynomial constraint.
            //
            // The polynomial expressions returned from `create_gate` will be
            // constrained by the proving system to equal zero. Our expression
            // has the following properties:
            // - When s_mul = 0, any value is allowed in lhs, rhs, and out.
            // - When s_mul != 0, this constrains lhs * rhs = out.
            vec![s_mul * (lhs * rhs - out)]
        });

        FieldConfig {
            advice,
            instance,
            s_mul,
        }
    }
}
// ANCHOR_END: chip-config

// ANCHOR: chip-impl
impl<F: Field> Chip<F> for FieldChip<F> {
    type Config = FieldConfig;
    type Loaded = ();

    fn config(&self) -> &Self::Config {
        &self.config
    }

    fn loaded(&self) -> &Self::Loaded {
        &()
    }
}
// ANCHOR_END: chip-impl

// ANCHOR: instructions-impl
/// A variable representing a number.
#[derive(Clone)]
struct Number<F: Field>(AssignedCell<F, F>);

impl<F: Field> NumericInstructions<F> for FieldChip<F> {
    type Num = Number<F>;

    fn load_private(
        &self,
        mut layouter: impl Layouter<F>,
        value: Value<F>,
    ) -> Result<Self::Num, Error> {
        let config = self.config();

        layouter.assign_region(
            || "load private",
            |mut region| {
                region
                    .assign_advice(|| "private input", config.advice[0], 0, || value)
                    .map(Number)
            },
        )
    }

    fn load_constant(
        &self,
        mut layouter: impl Layouter<F>,
        constant: F,
    ) -> Result<Self::Num, Error> {
        let config = self.config();

        layouter.assign_region(
            || "load constant",
            |mut region| {
                region
                    .assign_advice_from_constant(|| "constant value", config.advice[0], 0, constant)
                    .map(Number)
            },
        )
    }

    fn mul(
        &self,
        mut layouter: impl Layouter<F>,
        a: Self::Num,
        b: Self::Num,
    ) -> Result<Self::Num, Error> {
        let config = self.config();

        layouter.assign_region(
            || "mul",
            |mut region: Region<'_, F>| {
                // We only want to use a single multiplication gate in this region,
                // so we enable it at region offset 0; this means it will constrain
                // cells at offsets 0 and 1.
                config.s_mul.enable(&mut region, 0)?;

                // The inputs we've been given could be located anywhere in the circuit,
                // but we can only rely on relative offsets inside this region. So we
                // assign new cells inside the region and constrain them to have the
                // same values as the inputs.
                a.0.copy_advice(|| "lhs", &mut region, config.advice[0], 0)?;
                b.0.copy_advice(|| "rhs", &mut region, config.advice[1], 0)?;

                // Now we can assign the multiplication result, which is to be assigned
                // into the output position.
                let value = a.0.value().copied() * b.0.value();

                // Finally, we do the assignment to the output, returning a
                // variable to be used in another part of the circuit.
                region
                    .assign_advice(|| "lhs * rhs", config.advice[0], 1, || value)
                    .map(Number)
            },
        )
    }

    fn expose_public(
        &self,
        mut layouter: impl Layouter<F>,
        num: Self::Num,
        row: usize,
    ) -> Result<(), Error> {
        let config = self.config();

        layouter.constrain_instance(num.0.cell(), config.instance, row)
    }
}
// ANCHOR_END: instructions-impl

// ANCHOR: circuit
/// The full circuit implementation.
///
/// In this struct we store the private input variables. We use `Option<F>` because
/// they won't have any value during key generation. During proving, if any of these
/// were `None` we would get an error.
#[derive(Default)]
struct NoRickCircuit<F: Field> {
    r: F,                  // ASCII value for 'r'
    i: F,                  // ASCII value for 'i'
    c_val: F,              // ASCII value for 'c'
    k: F,                  // ASCII value for 'k'
    string: Vec<Value<F>>, // Fixed length of 20
}

impl<F: Field> Circuit<F> for NoRickCircuit<F> {
    // Since we are using a single chip for everything, we can just reuse its config.
    type Config = FieldConfig;
    type FloorPlanner = SimpleFloorPlanner;

    fn without_witnesses(&self) -> Self {
        Self::default()
    }

    fn configure(meta: &mut ConstraintSystem<F>) -> Self::Config {
        let advice = [meta.advice_column(), meta.advice_column()];
        let instance = meta.instance_column();
        let constant = meta.fixed_column();
        FieldChip::configure(meta, advice, instance, constant)
    }

    fn synthesize(
        &self,
        config: Self::Config,
        mut layouter: impl Layouter<F>,
    ) -> Result<(), Error> {
        let chip = FieldChip::<F>::construct(config);

        // Load all string characters as private inputs
        let mut chars = Vec::new();
        for (i, &char_val) in self.string.iter().enumerate() {
            let char_cell =
                chip.load_private(layouter.namespace(|| format!("load char {}", i)), char_val)?;
            chars.push(char_cell);
        }

        // Load constants for 'r','i','c','k' from circuit fields
        let r = chip.load_constant(layouter.namespace(|| "load r"), self.r)?;
        let i = chip.load_constant(layouter.namespace(|| "load i"), self.i)?;
        let c_val = chip.load_constant(layouter.namespace(|| "load c"), self.c_val)?;
        let k = chip.load_constant(layouter.namespace(|| "load k"), self.k)?;
        // Check for "rick" at every possible starting index (0 to 16)
        let mut conditions = Vec::new();
        for idx in 0..17 {
            let char0 = chars[idx].clone();
            let char1 = chars[idx + 1].clone();
            let char2 = chars[idx + 2].clone();
            let char3 = chars[idx + 3].clone();

            // Compute differences from 'r','i','c','k'
            let diff0_val = char0.0.value().copied() - r.0.value().copied();
            let diff1_val = char1.0.value().copied() - i.0.value().copied();
            let diff2_val = char2.0.value().copied() - c_val.0.value().copied();
            let diff3_val = char3.0.value().copied() - k.0.value().copied();

            // Load differences as private inputs
            let diff0 = chip.load_private(
                layouter.namespace(|| format!("load diff0 {}", idx)),
                diff0_val,
            )?;
            let diff1 = chip.load_private(
                layouter.namespace(|| format!("load diff1 {}", idx)),
                diff1_val,
            )?;
            let diff2 = chip.load_private(
                layouter.namespace(|| format!("load diff2 {}", idx)),
                diff2_val,
            )?;
            let diff3 = chip.load_private(
                layouter.namespace(|| format!("load diff3 {}", idx)),
                diff3_val,
            )?;

            // Multiply differences to get condition value (zero if match)
            let prod1 = chip.mul(layouter.namespace(|| format!("mul1 {}", idx)), diff0, diff1)?;
            let prod2 = chip.mul(layouter.namespace(|| format!("mul2 {}", idx)), prod1, diff2)?;
            let cond = chip.mul(layouter.namespace(|| format!("mul3 {}", idx)), prod2, diff3)?;
            conditions.push(cond);
        }

        // Compute product of all conditions
        let mut product = conditions[0].clone();
        for i in 1..conditions.len() {
            product = chip.mul(
                layouter.namespace(|| format!("mul conditions {}", i)),
                product,
                conditions[i].clone(),
            )?;
        }

        // Compute inverse of product (fails if product is zero)
        let inv_P_val = product.0.value().map(|p| p.invert().unwrap_or(F::ZERO));
        let inv_P = chip.load_private(layouter.namespace(|| "load inv_P"), inv_P_val)?;

        // Multiply product by its inverse; should be 1 if no match
        let product_times_inv =
            chip.mul(layouter.namespace(|| "product times inv"), product, inv_P)?;

        // Load constant 1
        let one = chip.load_constant(layouter.namespace(|| "load one"), F::ONE)?;

        // Constrain product_times_inv to equal 1 by binding both to the same instance cell
        layouter.constrain_instance(product_times_inv.0.cell(), chip.config().instance, 0)?;
        layouter.constrain_instance(one.0.cell(), chip.config().instance, 0)?;

        Ok(())
    }
}
// ANCHOR_END: circuit

// ANCHOR: dev-graph
fn main() {
    use halo2_proofs::dev::MockProver;

    // ANCHOR: test-circuit
    // The number of rows in our circuit cannot exceed 2^k. Since our example
    // circuit is very small, we can pick a very small value here.
    let k = 10; // Sufficient rows for the circuit

    // Test with "ricky" (contains "rick") - should fail
    let s1 = "ricky";

    let mut bytes1 = s1.as_bytes().to_vec();
    bytes1.resize(20, 0);
    let string_vec: Vec<Value<Fp>> = bytes1
        .iter()
        .map(|&b| Value::known(Fp::from(b as u64)))
        .collect();

    // In your test code:
    let mut circuit = NoRickCircuit {
        r: Fp::from(114u64),
        i: Fp::from(105u64),
        c_val: Fp::from(99u64),
        k: Fp::from(107u64),
        string: string_vec, // Your string values
    };
    // THE CONSTRAINT: set to one as we inverse constraint (if result == 0 , we know that the private input has "rick in it")
    let public_input = vec![Fp::one()];
    let prover1 = MockProver::run(k, &circuit, vec![public_input.clone()]).unwrap();
    assert!(prover1.verify().is_err());

    let s2 = "ronaldrickstien";
    let mut bytes2 = s2.as_bytes().to_vec();
    bytes2.resize(20, 0);
    let string_vec2: Vec<Value<Fp>> = bytes2
        .iter()
        .map(|&b| Value::known(Fp::from(b as u64)))
        .collect();

    circuit.string = string_vec2;

    let prover2 = MockProver::run(k, &circuit, vec![public_input]).unwrap();
    assert!(prover2.verify().is_err());

    let s3 = "randy";
    let mut bytes3 = s3.as_bytes().to_vec();
    bytes3.resize(20, 0);
    let string_vec3: Vec<Value<Fp>> = bytes3
        .iter()
        .map(|&b| Value::known(Fp::from(b as u64)))
        .collect();
    let circuit3 = NoRickCircuit {
        string: string_vec3,
    };
    let public_inputs3 = vec![Fp::one()];
    let prover3 = MockProver::run(k, &circuit3, vec![public_inputs3]).unwrap();
    assert!(prover3.verify().is_ok());

    // Create the area you want to draw on.
    // Use SVGBackend if you want to render to .svg instead.
    use plotters::prelude::*;
    let root = BitMapBackend::new("layout.png", (1024, 768)).into_drawing_area();
    root.fill(&WHITE).unwrap();
    let root = root
        .titled("Example Circuit Layout", ("sans-serif", 60))
        .unwrap();

    halo2_proofs::dev::CircuitLayout::default()
        // You can optionally render only a section of the circuit.
        .view_width(0..2)
        .view_height(0..16)
        // You can hide labels, which can be useful with smaller areas.
        .show_labels(true)
        // Render the circuit onto your area!
        // The first argument is the size parameter for the circuit.
        .render(10, &circuit, &root)
        .unwrap();

    // Generate the DOT graph string.
    let dot_string = halo2_proofs::dev::circuit_dot_graph(&circuit);

    // Now you can either handle it in Rust, or just
    // print it out to use with command-line tools.
    print!("{}", dot_string);
    // ANCHOR_END: test-circuit
}
// ANCHOR_END: dev-graph
