syntax = "proto3";

package headstash.actions.v1;

import "google/protobuf/struct.proto";


service HeadstashService {
      // retrieve token holder distribution
      rpc CreateHeadstashNotes(MsgCreateHeadstashNotes) returns (MsgCreateHeadstashNoteResponse);
      rpc CreateNewHeadstash(MsgCreateHeadstash) returns (MsgCreateHeadstashResponse);
      rpc PrepareNoteNullifier(MsgPrepareNoteNullifier) returns (MsgPrepareNoteNullifierResponse);
      // generate headstash instance tree
      rpc CreateHeadstashTree(MsgCreateHeadstashTree) returns (MsgCreateHeadstashTreeResponse);
      // determine piecewise distribution
      // prepare headstash config
      // create new headstash 
}

service HeadstashActionsService {
      // find new headstash
      // list headstash info 
      // perform headstash action
}

message MsgCreateHeadstashTreeResponse {}
message MsgCreateHeadstashTree {}
message MsgPrepareNoteNullifierResponse {}
message MsgPrepareNoteNullifier {}
message MsgCreateHeadstash {}
message MsgCreateHeadstashResponse {}
message MsgCreateHeadstashNotes {}
message MsgCreateHeadstashNoteResponse {}

message MsgClaimHeadstashNote {}
message MsgClaimHeadstashNoteResponse {}

 